# Simple Data Types and Basic Operators

In [0]:
name = 'iPhone 5S'

In [2]:
name

'iPhone 5S'

In [3]:
type(name)

str

In [4]:
screen_size = 4.3
type(screen_size)

float

In [5]:
num_of_speakers = 1
type(num_of_speakers)

int

In [6]:
print("I just bought an",name)

I just bought an iPhone 5S


In [7]:
print("I just bought an "+name)

I just bought an iPhone 5S


In [8]:
is_android = False
type(is_android)

bool

In [9]:
is_android==True

False

In [10]:
print(is_android==False and num_of_speakers>1)

False


# Code Blocks - If, for, while

In [11]:
if is_android==True:
  print("inside the if condition")
print("outside if")

outside if


In [12]:
for i in range(5):
  print(i)

0
1
2
3
4


In [0]:
range?

# Functions

In [0]:
def print_squares_with_startval(stopval,startval=0):
  """Prints the squares of the numbers in the given range, with stopval(exclusive) and startval(inclusive)"""
  
  for i in range(startval,stopval):
    print(i,i**2)

In [15]:
print_squares_with_startval(5,2)

2 4
3 9
4 16


In [16]:
help(print_squares_with_startval)

Help on function print_squares_with_startval in module __main__:

print_squares_with_startval(stopval, startval=0)
    Prints the squares of the numbers in the given range, with stopval(exclusive) and startval(inclusive)



In [0]:
print_squares_with_startval?

# Lists

In [0]:
my_phone = [name, is_android, screen_size]

In [19]:
my_phone

['iPhone 5S', False, 4.3]

In [20]:
type(my_phone)

list

In [21]:
type(my_phone[0])

str

In [22]:
my_phone[:2]

['iPhone 5S', False]

In [23]:
my_phone[1:3]

[False, 4.3]

In [24]:
my_phone[1:]

[False, 4.3]

In [0]:
my_dad_phone = my_phone

In [26]:
print(my_dad_phone)

['iPhone 5S', False, 4.3]


In [0]:
my_phone[2] = 4

In [28]:
my_phone

['iPhone 5S', False, 4]

In [29]:
##Changes in my_phone get reflected here, i.e. the copy is shallow, or the reference is being shared between the two objects
print(my_dad_phone)

['iPhone 5S', False, 4]


In [0]:
my_dad_phone2 = list(my_phone)

In [31]:
my_dad_phone2

['iPhone 5S', False, 4]

In [0]:
my_phone[2] = 4.2

In [33]:
my_dad_phone2

['iPhone 5S', False, 4]

In [0]:
my_dad_phone3 = my_phone.copy()

In [35]:
my_dad_phone3

['iPhone 5S', False, 4.2]

In [0]:
my_phone[2] = 5

In [37]:
my_dad_phone3

['iPhone 5S', False, 4.2]

In [38]:
##Returns the no. of elements in the list
len(my_phone)

3

In [0]:
my_phone.append('3g')

In [40]:
len(my_phone)

4

In [41]:
my_phone

['iPhone 5S', False, 5, '3g']

In [0]:
iphone_some_prefs = ['single_sim',35000]

In [0]:
my_phone+=iphone_some_prefs

In [44]:
##Concatenates the two lists into the first
my_phone

['iPhone 5S', False, 5, '3g', 'single_sim', 35000]

In [0]:
## Doesn't work
# my_phone+=5

In [0]:
## Doesn't work even if all member elements are integers

# my_list = [10,15]
# my_list+=5

In [45]:
for data in my_phone:
  print(data)

iPhone 5S
False
5
3g
single_sim
35000


In [46]:
list(range(5))

[0, 1, 2, 3, 4]

In [0]:
'''map() function returns a list of the results after applying the given function to each item of a given iterable (list, tuple etc.)'''

a = list(range(5))
b = list(map(lambda x:x**2, a))

In [48]:
b

[0, 1, 4, 9, 16]

In [0]:
#applies the function sent in as parameter on each element of the list and includes the one which returns true 
c = list(filter(lambda x : x%2==0,b))

In [50]:
c

[0, 4, 16]

# Tuples

In [0]:
##Tuples are immutable
my_phone_tuple = (name,is_android,screen_size)

In [52]:
type(my_phone_tuple)

tuple

In [53]:
import time

tic = time.time()
print(tic)

1566827057.1345465


In [0]:
"""Return the current time in seconds since the Epoch.
Fractions of a second may be present if the system clock provides them."""

time.time?

In [55]:
tic = time.time()
toc = time.time()

print("elapsed time:", toc-tic)

elapsed time: 1.4781951904296875e-05


In [56]:
my_list = list(range(10000000))
tic = time.time()
my_list_squared = list(map(lambda x:x**2,my_list))
toc = time.time()
print(toc-tic)

2.861056089401245


In [57]:
my_tuple = tuple(range(10000000))
tic = time.time()
my_tuple_squared = tuple(map(lambda x:x**2,my_tuple))
toc = time.time()
print(toc-tic)

2.8290517330169678


# Sets

In [0]:
my_set = set(my_phone)

In [59]:
my_set

{35000, '3g', 5, False, 'iPhone 5S', 'single_sim'}

In [0]:
my_set2 = {1,2,3,4,1,2,2,3}

In [61]:
my_set2

{1, 2, 3, 4}

In [62]:
my_list = list(range(10000000))
tic = time.time()
print(10098 in my_list)
print(1000000000 in my_list)
print(988821 in my_list)

toc = time.time()
print(toc-tic)

True
False
True
0.11829090118408203


In [63]:
##Queries to sets are much faster than in lists, where also sets store unique values only

my_set = set(range(10000000))
tic = time.time()
print(10098 in my_set)
print(1000000000 in my_set)
print(988821 in my_set)

toc = time.time()
print(toc-tic)

True
False
True
0.000469207763671875


In [0]:
my_set = set()
my_set.add(10)

In [100]:
##Set stores object in sorted order

aux = {10,8,9,6,5,6,4}
aux

{4, 5, 6, 8, 9, 10}

# Dicts

In [0]:
my_dict = {}

In [66]:
type(my_dict)

dict

In [0]:
my_dict["name"] = "iPhone 5s"
my_dict["isAndroid"] = False
my_dict["screen_size"] = 4.3

In [68]:
my_dict.keys()

dict_keys(['name', 'isAndroid', 'screen_size'])

In [101]:
list(my_dict.keys())

['name', 'isAndroid', 'screen_size']

In [69]:
my_dict.values()

dict_values(['iPhone 5s', False, 4.3])

In [70]:
my_dict["name"]

'iPhone 5s'

In [71]:
my_dict.items()

dict_items([('name', 'iPhone 5s'), ('isAndroid', False), ('screen_size', 4.3)])

# Python packages

In [0]:
import math

In [73]:
math.sqrt(16)

4.0

In [74]:
math.pow(4,2)

16.0

In [0]:
import math as m

In [76]:
m.factorial(10)

3628800

In [0]:
from math import factorial as fact

In [78]:
fact(12)

479001600

In [79]:
m.pi

3.141592653589793

Creating own package from psuedo terminal.

In [0]:
!touch my_first_package.py

In [0]:
!echo "def hello():" >> my_first_package.py

In [82]:
!cat my_first_package.py

def hello():


In [0]:
!echo "  print('This is my city')" >> my_first_package.py

In [84]:
!cat my_first_package.py

def hello():
  print('This is my city')


In [0]:
import my_first_package as mi

In [86]:
mi.hello()

This is my city


# File Handling

In [87]:
!ls

my_first_package.py  __pycache__  sample_data


In [88]:
!wget https://s3.amazonaws.com/thinkific-import/153034/mobile_cleaned-1549119762886.csv

--2019-08-26 13:44:41--  https://s3.amazonaws.com/thinkific-import/153034/mobile_cleaned-1549119762886.csv
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.99.149
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.99.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14044 (14K) [text/csv]
Saving to: ‘mobile_cleaned-1549119762886.csv’

mobile_cleaned-1549 100%[===================>]  13.71K  --.-KB/s    in 0s      

2019-08-26 13:44:41 (280 MB/s) - ‘mobile_cleaned-1549119762886.csv’ saved [14044/14044]



In [89]:
!ls

mobile_cleaned-1549119762886.csv  my_first_package.py  __pycache__  sample_data


In [0]:
!mv mobile_cleaned-1549119762886.csv mobile_cleaned.csv

In [103]:
!ls

mobile_cleaned.csv  my_first_package.py  __pycache__  sample_data


In [0]:
file = open("mobile_cleaned.csv",'r')

In [0]:
s = file.readline()

In [106]:
s

'sim_type,aperture,gpu_rank,weight,stand_by_time,processor_frequency,thickness,flash_type,front_camera_resolution,auto_focus,screen_size,frames_per_second,FM,no_of_reviews_in_gsmarena_in_week,os,phone_height,screen_protection,sim_size,price,talk_time,video_resolution,display_resolution,removable_battery,display_type,primary_camera_resolution,battery_type,ram_memory,internal_memory,brand_rank,no_of_cores,micro_sd_slot,screen_pixel_density,water_proof_rate,phone_width,expandable_memory,version,usb_type,battery_capacity,processor_rank,is_liked\n'

In [107]:
s.split(',')

['sim_type',
 'aperture',
 'gpu_rank',
 'weight',
 'stand_by_time',
 'processor_frequency',
 'thickness',
 'flash_type',
 'front_camera_resolution',
 'auto_focus',
 'screen_size',
 'frames_per_second',
 'FM',
 'no_of_reviews_in_gsmarena_in_week',
 'os',
 'phone_height',
 'screen_protection',
 'sim_size',
 'price',
 'talk_time',
 'video_resolution',
 'display_resolution',
 'removable_battery',
 'display_type',
 'primary_camera_resolution',
 'battery_type',
 'ram_memory',
 'internal_memory',
 'brand_rank',
 'no_of_cores',
 'micro_sd_slot',
 'screen_pixel_density',
 'water_proof_rate',
 'phone_width',
 'expandable_memory',
 'version',
 'usb_type',
 'battery_capacity',
 'processor_rank',
 'is_liked\n']

In [0]:
file.close()

In [109]:
with open('mobile_cleaned.csv','r') as file:
  line = file.readline().split(',')
  print(line)

['sim_type', 'aperture', 'gpu_rank', 'weight', 'stand_by_time', 'processor_frequency', 'thickness', 'flash_type', 'front_camera_resolution', 'auto_focus', 'screen_size', 'frames_per_second', 'FM', 'no_of_reviews_in_gsmarena_in_week', 'os', 'phone_height', 'screen_protection', 'sim_size', 'price', 'talk_time', 'video_resolution', 'display_resolution', 'removable_battery', 'display_type', 'primary_camera_resolution', 'battery_type', 'ram_memory', 'internal_memory', 'brand_rank', 'no_of_cores', 'micro_sd_slot', 'screen_pixel_density', 'water_proof_rate', 'phone_width', 'expandable_memory', 'version', 'usb_type', 'battery_capacity', 'processor_rank', 'is_liked\n']


In [0]:
with open('mobile_cleaned.csv','r') as file:
  print(file.read())

In [0]:
with open('mobile_cleaned.csv','r') as file:
  for line in file:
    for word in line.split(','):
      print(word,end=" ")
    print()

In [0]:
with open('my_out.txt','w') as file:
  file.write("hello from python code")

In [115]:
!cat my_out.txt

hello from python code

# Class

In [0]:
class MobilePhone:
  
  """This class defines mobile phone class with specific variable and functions"""
  def __init__(self,name,is_android=False,screen_size=4.3):
    self.name = name
    self.is_android = is_android
    self.screen_size = screen_size
    
  def __repr__(self):
    return self.name
  
  def __str__(self):
    return self.name + " " + self.is_android

In [0]:
new_phone = MobilePhone("iPhone 5s")

In [131]:
##Returns the object that the repr function has been asked to return.

new_phone

iPhone 5s

In [125]:
type(new_phone)

__main__.MobilePhone

In [126]:
new_phone.name

'iPhone 5s'

In [128]:
##Accessing the docstring of the object

MobilePhone.__doc__

'This class defines mobile phone class with specific variable and functions'

In [0]:
class iPhone(MobilePhone):
  
  def __init__(self,name):
    
    MobilePhone.__init__(self,name,False,3.9)

In [0]:
current_phone = iPhone("iPhone 5")

In [134]:
current_phone

iPhone 5

# Numpy

In [0]:
import numpy as np

In [0]:
l = [3,4,5]

In [0]:
X = np.array(l)

In [138]:
X

array([3, 4, 5])

In [139]:
type(X)

numpy.ndarray

In [0]:
Y = np.asarray(l,float)

In [141]:
Y

array([3., 4., 5.])

In [142]:
type(Y)

numpy.ndarray

In [144]:
print(X.shape)
print(Y.shape)

(3,)
(3,)


In [0]:
l2 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [0]:
Z = np.array(l2)

In [147]:
Z.shape

(3, 4)

In [148]:
Z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [149]:
Z.sum()

78

In [150]:
Z.sum(axis=1)

array([10, 26, 42])

In [151]:
Z.sum(axis=0)

array([15, 18, 21, 24])

In [152]:
Z.max(axis=1)

array([ 4,  8, 12])

In [153]:
Z.mean()

6.5

In [154]:
Z.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [155]:
Z.mean(axis=0)

array([5., 6., 7., 8.])

In [0]:
l3 = [[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]]

In [0]:
U = np.array(l3)

In [158]:
U.shape

(3, 2, 4)

In [162]:
U.sum(axis=1)

array([[ 6,  8, 10, 12],
       [22, 24, 26, 28],
       [38, 40, 42, 44]])

In [163]:
U.sum(axis=0)

array([[27, 30, 33, 36],
       [39, 42, 45, 48]])

In [164]:
U.sum(axis=2)

array([[10, 26],
       [42, 58],
       [74, 90]])

In [0]:
l4 = [[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]],[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]]]

In [0]:
V = np.array(l4)

In [167]:
V

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[17, 18, 19, 20],
         [21, 22, 23, 24]]]])

In [168]:
V.shape

(2, 3, 2, 4)

In [169]:
V.sum(axis=0)

array([[[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[18, 20, 22, 24],
        [26, 28, 30, 32]],

       [[34, 36, 38, 40],
        [42, 44, 46, 48]]])

In [170]:
V.sum(axis=1)

array([[[27, 30, 33, 36],
        [39, 42, 45, 48]],

       [[27, 30, 33, 36],
        [39, 42, 45, 48]]])

In [171]:
V.sum(axis=2)

array([[[ 6,  8, 10, 12],
        [22, 24, 26, 28],
        [38, 40, 42, 44]],

       [[ 6,  8, 10, 12],
        [22, 24, 26, 28],
        [38, 40, 42, 44]]])

In [172]:
V.sum(axis=3)

array([[[10, 26],
        [42, 58],
        [74, 90]],

       [[10, 26],
        [42, 58],
        [74, 90]]])

In [0]:
Q = np.ones((3,4))

In [0]:
##to create array with diagonal elements as 1

W = np.eye(4,4)

In [179]:
W

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
C = np.ones((3,4))

In [198]:
print(Q)
print()
print(C)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [0]:
p = np.inner(Q,C)

In [200]:
p

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [0]:
o = np.outer(Q,C)

In [186]:
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [207]:
o.shape

(12, 12)

In [0]:
d = np.dot(Q,C.T)

In [189]:
d

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [0]:
e = np.ones(4)

In [0]:
f = np.ones(4)

In [192]:
np.inner(e,f)

4.0

In [202]:
a = np.ones((5,4))
b = np.ones((3,4))

np.inner(a,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [209]:
np.outer(a,b).shape

(20, 12)

In [0]:
c = np.array([3,3,3])
d = np.array([[4,4,4],[5,5,5]])

In [206]:
np.inner(c,d)

array([36, 45])

In [210]:
np.outer(c,d)

array([[12, 12, 12, 15, 15, 15],
       [12, 12, 12, 15, 15, 15],
       [12, 12, 12, 15, 15, 15]])

In [0]:
g = np.random.random((4,5))

In [212]:
g

array([[0.31270611, 0.99807723, 0.49831516, 0.58038069, 0.22215489],
       [0.78013089, 0.95870518, 0.79722525, 0.22601973, 0.41937195],
       [0.82787246, 0.21087994, 0.38479797, 0.93658687, 0.79105659],
       [0.53061217, 0.51269502, 0.00362107, 0.60077858, 0.38944538]])

In [213]:
g+1

array([[1.31270611, 1.99807723, 1.49831516, 1.58038069, 1.22215489],
       [1.78013089, 1.95870518, 1.79722525, 1.22601973, 1.41937195],
       [1.82787246, 1.21087994, 1.38479797, 1.93658687, 1.79105659],
       [1.53061217, 1.51269502, 1.00362107, 1.60077858, 1.38944538]])

In [217]:
h = np.floor(np.random.random((5,6))*10)
h

array([[0., 1., 4., 7., 0., 4.],
       [4., 9., 7., 2., 3., 3.],
       [7., 6., 3., 1., 7., 4.],
       [8., 9., 8., 7., 0., 0.],
       [7., 7., 5., 0., 1., 1.]])